## WH with timeseries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing

In [2]:
df = pd.read_excel("C:\\Users\\dagani\\OneDrive - HP Inc\\Itay General\\Machine learning\\DFfinal.xlsm")
X = df.drop(['y'], axis=1)

Y=df.groupby('SN').mean('y')
y=(Y['y']).astype(int)
y.value_counts()/len(y)

1    0.575269
0    0.424731
Name: y, dtype: float64

In [3]:
y

SN
800061001    1
800301002    1
800511003    1
800571004    1
800601005    1
            ..
802801106    1
802801185    0
802821107    1
802831186    0
802841187    0
Name: y, Length: 186, dtype: int32

In [4]:
from tsfresh import extract_features
from tsfresh.feature_extraction import MinimalFCParameters
from tsfresh.feature_extraction import ComprehensiveFCParameters

settings = MinimalFCParameters()
#settings = ComprehensiveFCParameters()

extracted_features = extract_features(X,column_id='SN', column_sort='time',default_fc_parameters=settings)

Feature Extraction: 100%|██████████████████████████████████████████████████████████████| 30/30 [00:04<00:00,  6.12it/s]


In [5]:
extracted_features

F1_IS_NT__sum_values  F1_IS_NT__median  F1_IS_NT__mean  \
800061001               -643.13           -32.075        -32.1565   
800301002               -580.10           -29.360        -29.0050   
800511003               -475.97           -23.530        -23.7985   
800571004               -637.07           -32.325        -31.8535   
800601005               -526.58           -26.065        -26.3290   
...                         ...               ...             ...   
802801106               -739.24           -36.685        -36.9620   
802801185               -553.20           -27.300        -27.6600   
802821107               -494.15           -24.760        -24.7075   
802831186               -494.54           -24.880        -24.7270   
802841187               -505.34           -25.305        -25.2670   

           F1_IS_NT__length  F1_IS_NT__standard_deviation  F1_IS_NT__variance  \
800061001              20.0                      0.904059            0.817323   
800301002              20.0                      1.579283            2.494135   
800511003              20.0                      0.966718            0.934543   
800571004              20.0                      1.382875            1.912343   
800601005              20.0                      0.792268            0.627689   
...                     ...                           ...                 ...   
802801106              20.0                      1.172560            1.374896   
802801185              20.0                      1.567766            2.457890   
802821107              20.0                      1.964260            3.858319   
802831186              20.0                      0.962960            0.927291   
802841187              20.0                      2.030850            4.124351   

           F1_IS_NT__root_mean_square  F1_IS_NT__maximum  \
800061001                   32.169206             -29.73   
800301002                   29.047963             -26.64   
800511003                   23.818126             -22.37   
800571004                   31.883504             -28.55   
800601005                   26.340917             -25.19   
...                               ...                ...   
802801106                   36.980594             -34.84   
802801185                   27.704395             -24.72   
802821107                   24.785457             -21.76   
802831186                   24.745743             -22.86   
802841187                   25.348484             -21.91   

           F1_IS_NT__absolute_maximum  F1_IS_NT__minimum  ...  \
800061001                       33.79             -33.79  ...   
800301002                       31.72             -31.72  ...   
800511003                       26.07             -26.07  ...   
800571004                       33.37             -33.37  ...   
800601005                       27.53             -27.53  ...   
...                               ...                ...  ...   
802801106                       39.41             -39.41  ...   
802801185                       30.79             -30.79  ...   
802821107                       28.13             -28.13  ...   
802831186                       25.94             -25.94  ...   
802841187                       28.58             -28.58  ...   

           L40_CS_T__sum_values  L40_CS_T__median  L40_CS_T__mean  \
800061001                  3.67             0.095          0.1835   
800301002                  2.22             0.100          0.1110   
800511003                  0.70             0.080          0.0350   
800571004                 -2.98            -0.090         -0.1490   
800601005                  4.32             0.095          0.2160   
...                         ...               ...             ...   
802801106                 -0.30             0.045         -0.0150   
802801185                  1.04             0.130          0.0520   
802821107                  3.21             0.130          0.1605   
802831186        

In [6]:
index=extracted_features.index
X = preprocessing.StandardScaler().fit_transform(extracted_features)
extracted_features = pd.DataFrame(X, columns=extracted_features.columns)
extracted_features.index=index

In [7]:
extracted_features

F1_IS_NT__sum_values  F1_IS_NT__median  F1_IS_NT__mean  \
800061001             -0.841413         -0.811058       -0.841413   
800301002             -0.055672         -0.134861       -0.055672   
800511003              1.242427          1.317158        1.242427   
800571004             -0.765868         -0.873323       -0.765868   
800601005              0.611516          0.685792        0.611516   
...                         ...               ...             ...   
802801106             -2.039534         -1.959224       -2.039534   
802801185              0.279667          0.378203        0.279667   
802821107              1.015793          1.010815        1.015793   
802831186              1.010931          0.980928        1.010931   
802841187              0.876297          0.875077        0.876297   

           F1_IS_NT__length  F1_IS_NT__standard_deviation  F1_IS_NT__variance  \
800061001               0.0                     -0.792602           -0.752453   
800301002               0.0                      0.415694            0.211190   
800511003               0.0                     -0.680477           -0.685088   
800571004               0.0                      0.064226           -0.123159   
800601005               0.0                     -0.992649           -0.861433   
...                     ...                           ...                 ...   
802801106               0.0                     -0.312128           -0.432023   
802801185               0.0                      0.395084            0.190360   
802821107               0.0                      1.104600            0.995169   
802831186               0.0                     -0.687201           -0.689256   
802841187               0.0                      1.223760            1.148054   

           F1_IS_NT__root_mean_square  F1_IS_NT__maximum  \
800061001                    0.836926          -0.775471   
800301002                    0.056996          -0.037493   
800511003                   -1.249825           0.982301   
800571004                    0.765536          -0.493655   
800601005                   -0.619435           0.308807   
...                               ...                ...   
802801106                    2.039186          -1.995881   
802801185                   -0.278732           0.421056   
802821107                   -1.008110           1.127986   
802831186                   -1.018034           0.865276   
802841187                   -0.867422           1.092162   

           F1_IS_NT__absolute_maximum  F1_IS_NT__minimum  ...  \
800061001                    0.691025          -0.691025  ...   
800301002                    0.172787          -0.172787  ...   
800511003                   -1.241729           1.241729  ...   
800571004                    0.585875          -0.585875  ...   
800601005                   -0.876208           0.876208  ...   
...                               ...                ...  ...   
802801106                    2.098030          -2.098030  ...   
802801185                   -0.060045           0.060045  ...   
802821107                   -0.725994           0.725994  ...   
802831186                   -1.274275           1.274275  ...   
802841187                   -0.613334           0.613334  ...   

           L40_CS_T__sum_values  L40_CS_T__median  L40_CS_T__mean  \
800061001              1.341667          0.534111        1.341667   
800301002              0.721226          0.573101        0.721226   
800511003              0.070832          0.417144        0.070832   
800571004             -1.503805         -0.908492       -1.503805   
800601005              1.619796          0.534111        1.619796   
...                         ...               ...             ...   
802801106             -0.357059          0.144218       -0.357059   
802801185              0.216315          0.807036        0.216315   
802821107              1.144837          0.807036        1.144837   
802831186        

In [8]:
from sklearn import model_selection

X_train, X_test, y_train, y_test = model_selection.train_test_split(extracted_features, y, test_size=0.30, stratify=y, random_state=42)

len(X_train), len(X_test)

(130, 56)

In [9]:
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

model = KNeighborsClassifier()
model.fit(X_train, y_train)
y_preds = model.predict(X_test)

print(metrics.confusion_matrix(y_test, y_preds))
print(metrics.classification_report(y_test, y_preds))

[[12 12]
 [ 8 24]]
              precision    recall  f1-score   support

           0       0.60      0.50      0.55        24
           1       0.67      0.75      0.71        32

    accuracy                           0.64        56
   macro avg       0.63      0.62      0.63        56
weighted avg       0.64      0.64      0.64        56



In [10]:
from sklearn import model_selection



from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = model_selection.train_test_split(extracted_features, y, test_size=0.20, stratify=y, random_state=42)
model = RandomForestClassifier(n_estimators=50, random_state=42)
model.fit(X_train, y_train)

y_preds = model.predict(X_test)

print(metrics.confusion_matrix(y_test, y_preds))
print(metrics.classification_report(y_test, y_preds))

[[10  6]
 [11 11]]
              precision    recall  f1-score   support

           0       0.48      0.62      0.54        16
           1       0.65      0.50      0.56        22

    accuracy                           0.55        38
   macro avg       0.56      0.56      0.55        38
weighted avg       0.58      0.55      0.55        38



In [11]:
X=extracted_features

In [12]:
from mrmr import mrmr_classif

for i in range(10, len(X_train.columns)-330 + 1):
    # use mrmr classification
    selected_features = mrmr_classif(X, y, K = i)
    model = KNeighborsClassifier()
    model.fit(X_train[selected_features], y_train)
    y_preds = model.predict(X_test[selected_features])

    print(i)
    print(metrics.confusion_matrix(y_test, y_preds))    

100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 16.25it/s]


10
[[ 7  9]
 [10 12]]


100%|██████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 22.82it/s]


11
[[ 7  9]
 [ 9 13]]


100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 23.36it/s]


12
[[ 8  8]
 [ 9 13]]


100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 23.19it/s]


13
[[ 7  9]
 [ 7 15]]


100%|██████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 22.47it/s]


14
[[ 6 10]
 [ 7 15]]


100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 22.80it/s]


15
[[ 6 10]
 [ 8 14]]


100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 22.35it/s]


16
[[ 6 10]
 [ 7 15]]


100%|██████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 22.36it/s]


17
[[ 6 10]
 [ 9 13]]


100%|██████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 22.94it/s]


18
[[ 6 10]
 [ 9 13]]


100%|██████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 22.20it/s]


19
[[ 6 10]
 [ 8 14]]


100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 23.26it/s]


20
[[ 8  8]
 [ 7 15]]


100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 23.60it/s]


21
[[ 7  9]
 [ 7 15]]


100%|██████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 22.97it/s]


22
[[ 8  8]
 [ 7 15]]


100%|██████████████████████████████████████████████████████████████████████████████████| 23/23 [00:01<00:00, 21.30it/s]


23
[[ 8  8]
 [ 8 14]]


100%|██████████████████████████████████████████████████████████████████████████████████| 24/24 [00:01<00:00, 20.94it/s]


24
[[ 8  8]
 [ 8 14]]


100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:01<00:00, 19.94it/s]


25
[[ 7  9]
 [ 8 14]]


100%|██████████████████████████████████████████████████████████████████████████████████| 26/26 [00:01<00:00, 21.40it/s]


26
[[ 8  8]
 [ 9 13]]


100%|██████████████████████████████████████████████████████████████████████████████████| 27/27 [00:01<00:00, 22.70it/s]


27
[[ 8  8]
 [ 9 13]]


100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:01<00:00, 23.47it/s]


28
[[ 8  8]
 [ 9 13]]


100%|██████████████████████████████████████████████████████████████████████████████████| 29/29 [00:01<00:00, 23.42it/s]


29
[[ 8  8]
 [ 8 14]]


100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:01<00:00, 23.47it/s]


30
[[ 8  8]
 [ 8 14]]


In [13]:
selected_features = mrmr_classif(X, y, K = 100)
model1 = KNeighborsClassifier()
model1.fit(X_train[selected_features], y_train)
y_preds = model1.predict(X_test[selected_features])

model2 = RandomForestClassifier(n_estimators=50, random_state=42)
model2.fit(X_train[selected_features], y_train)
y_preds2 = model2.predict(X_test[selected_features])

print(metrics.confusion_matrix(y_test, y_preds))    
print(metrics.classification_report(y_test, y_preds))

print(metrics.confusion_matrix(y_test, y_preds2))    
print(metrics.classification_report(y_test, y_preds2))

100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:04<00:00, 24.28it/s]


[[ 9  7]
 [ 5 17]]
              precision    recall  f1-score   support

           0       0.64      0.56      0.60        16
           1       0.71      0.77      0.74        22

    accuracy                           0.68        38
   macro avg       0.68      0.67      0.67        38
weighted avg       0.68      0.68      0.68        38

[[10  6]
 [ 9 13]]
              precision    recall  f1-score   support

           0       0.53      0.62      0.57        16
           1       0.68      0.59      0.63        22

    accuracy                           0.61        38
   macro avg       0.61      0.61      0.60        38
weighted avg       0.62      0.61      0.61        38



In [91]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense

# Assuming you have your features (X) and labels (y) ready

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the input features using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define the neural network architecture
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(360,)))  # Input layer
model.add(Dense(64, activation='relu'))  # Hidden layer
model.add(Dense(1, activation='sigmoid'))  # Output layer

# Compile the model
model.compile(tf.keras.optimizers.Adam(lr=0.0001), loss='binary_crossentropy', metrics=['accuracy'],)

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=1, verbose=1)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f'Test Loss: {loss:.4f}')
print(f'Test Accuracy: {accuracy:.4f}')

# Make predictions on new data
#new_data = ...  # Your new data to make predictions on
#scaled_new_data = scaler.transform(new_data)
#predictions = model.predict_classes(scaled_new_data)


Epoch 1/10
148/148 [==============================] - 1s 2ms/step - loss: 0.7333 - accuracy: 0.5135
Epoch 2/10
148/148 [==============================] - 0s 2ms/step - loss: 0.6409 - accuracy: 0.6149
Epoch 3/10
148/148 [==============================] - 0s 2ms/step - loss: 0.5816 - accuracy: 0.7568
Epoch 4/10
148/148 [==============================] - 0s 3ms/step - loss: 0.5374 - accuracy: 0.7838
Epoch 5/10
148/148 [==============================] - 0s 2ms/step - loss: 0.5037 - accuracy: 0.8108
Epoch 6/10
148/148 [==============================] - 0s 2ms/step - loss: 0.4655 - accuracy: 0.8378
Epoch 7/10
148/148 [==============================] - 0s 2ms/step - loss: 0.4394 - accuracy: 0.8514
Epoch 8/10
148/148 [==============================] - 0s 2ms/step - loss: 0.4103 - accuracy: 0.8784
Epoch 9/10
148/148 [==============================] - 0s 2ms/step - loss: 0.3896 - accuracy: 0.8851
Epoch 10/10
148/148 [==============================] - 0s 2ms/step - loss: 0.3649 - accuracy: 0.8784